export const balancedLevels = [
  // 🟢 FÁCEIS — ideal para aprendizado
  {
    level: 1,
    gridSize: 4,
    pairs: 6,
    color: 'green-6',
    textColor: 'white',
    deck: 'easy',
    allowEqualCards: 0,
  },
  {
    level: 2,
    gridSize: 4,
    pairs: 8,
    color: 'lime-6',
    textColor: 'black',
    deck: 'easy',
    allowEqualCards: 0,
  },
  {
    level: 3,
    gridSize: 4,
    pairs: 10,
    color: 'amber-6',
    textColor: 'white',
    deck: 'easy',
    allowEqualCards: 1,
  },
  {
    level: 4,
    gridSize: 5,
    pairs: 10,
    color: 'cyan-6',
    textColor: 'white',
    deck: 'easy',
    allowEqualCards: 1,
  },
  {
    level: 5,
    gridSize: 5,
    pairs: 12,
    color: 'teal-6',
    textColor: 'white',
    deck: 'easy',
    allowEqualCards: 2,
  },

  // 🟡 NORMAIS — começam a exigir mais atenção
  {
    level: 6,
    gridSize: 5,
    pairs: 14,
    color: 'blue-6',
    textColor: 'white',
    deck: 'normal',
    allowEqualCards: 2,
  },
  {
    level: 7,
    gridSize: 5,
    pairs: 15,
    color: 'purple-6',
    textColor: 'white',
    deck: 'normal',
    allowEqualCards: 3,
  },
  {
    level: 8,
    gridSize: 6,
    pairs: 15,
    color: 'deep-orange-6',
    textColor: 'white',
    deck: 'normal',
    allowEqualCards: 3,
  },
  {
    level: 9,
    gridSize: 6,
    pairs: 16,
    color: 'indigo-6',
    textColor: 'white',
    deck: 'normal',
    allowEqualCards: 4,
  },
  {
    level: 10,
    gridSize: 6,
    pairs: 18,
    color: 'pink-6',
    textColor: 'white',
    deck: 'normal',
    allowEqualCards: 4,
  },

  // 🔴 DIFÍCEIS — mais pares e mais cartas similares
  {
    level: 11,
    gridSize: 6,
    pairs: 18,
    color: 'deep-purple-6',
    textColor: 'white',
    deck: 'hard',
    allowEqualCards: 5,
  },
  {
    level: 12,
    gridSize: 6,
    pairs: 20,
    color: 'orange-6',
    textColor: 'white',
    deck: 'hard',
    allowEqualCards: 6,
  },
  {
    level: 13,
    gridSize: 6,
    pairs: 22,
    color: 'blue-grey-6',
    textColor: 'white',
    deck: 'hard',
    allowEqualCards: 7,
  },
  {
    level: 14,
    gridSize: 7,
    pairs: 24,
    color: 'red-6',
    textColor: 'white',
    deck: 'hard',
    allowEqualCards: 8,
  },
  {
    level: 15,
    gridSize: 7,
    pairs: 26,
    color: 'brown-6',
    textColor: 'white',
    deck: 'hard',
    allowEqualCards: 9,
  },

  // 🟣 SUPER DIFÍCEIS — “modo inferno” e boss levels
  {
    level: 16,
    gridSize: 7,
    pairs: 28,
    color: 'deep-orange-9',
    textColor: 'white',
    deck: 'super-hard',
    allowEqualCards: 10,
  },
  {
    level: 17,
    gridSize: 7,
    pairs: 30,
    color: 'purple-10',
    textColor: 'yellow-3',
    deck: 'super-hard',
    allowEqualCards: 12,
  },
  {
    level: 18,
    gridSize: 8,
    pairs: 32,
    color: 'grey-9',
    textColor: 'white',
    deck: 'super-hard',
    allowEqualCards: 14,
  },
  {
    level: 19,
    gridSize: 8,
    pairs: 34,
    color: 'black',
    textColor: 'amber-4',
    deck: 'super-hard',
    allowEqualCards: 16,
  },
  {
    level: 20,
    gridSize: 8,
    pairs: 36,
    color: 'black',
    textColor: 'red-5',
    deck: 'boss',
    allowEqualCards: 20, // nível final, máximo desafio
  },
];
