const levelsConfig = [
  {
    level: 1,
    gridSize: 4,
    pairs: 8,
    color: 'green-6',
    textColor: 'white',
    deck: 'default',
  },
  {
    level: 2,
    gridSize: 5,
    pairs: 10,
    color: 'amber-6',
    textColor: 'white',
    deck: 'default',
  },
  {
    level: 3,
    gridSize: 5,
    pairs: 10,
    color: 'red-6',
    textColor: 'white',
    deck: 'default',
  },
  {
    level: 4,
    gridSize: 5,
    pairs: 12,
    color: 'blue-6',
    textColor: 'white',
    deck: 'default',
  },
  {
    level: 5,
    gridSize: 6,
    pairs: 12,
    color: 'purple-6',
    textColor: 'white',
    deck: 'default',
  },
  {
    level: 6,
    gridSize: 5,
    pairs: 15,
    color: 'deep-orange-6',
    textColor: 'white',
    deck: 'hard',
  },
  {
    level: 7,
    gridSize: 6,
    pairs: 15,
    color: 'teal-6',
    textColor: 'white',
    deck: 'hard',
  },
  {
    level: 8,
    gridSize: 6,
    pairs: 18,
    color: 'indigo-6',
    textColor: 'white',
    deck: 'hard',
  },
  {
    level: 9,
    gridSize: 4,
    pairs: 12,
    color: 'pink-6',
    textColor: 'white',
    deck: 'hard',
  },
  {
    level: 10,
    gridSize: 6,
    pairs: 18,
    color: 'black',
    textColor: 'yellow-4',
    deck: 'hard',
  },
];

export default levelsConfig;
